# -*- coding: utf-8 -*-
"""train_regression_models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mxb5ANLMF1l0sSu43Y-kMVV1jL_Ef9yb
"""

import json
import joblib
import numpy as np
import pandas as pd

from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

RANDOM_STATE = 42

# ================================
# 1. LOAD DATA
# ================================
diabetes = load_diabetes()
X = pd.DataFrame(diabetes.data, columns=diabetes.feature_names)
y = diabetes.target

feature_names = list(X.columns)

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE
)

# ================================
# 2. TRAIN MODELS
# ================================

models = {}

# ---- Linear Regression ----
pipe_lr = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LinearRegression())
])
pipe_lr.fit(X_train, y_train)
models["linear"] = pipe_lr

# ---- Ridge Regression (Grid Search) ----
alpha = np.logspace(-3, 3, 7)
param_grid_ridge = {"model__alpha": alpha}

pipe_ridge = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Ridge(max_iter=5000, random_state=RANDOM_STATE))
])

grid_ridge = GridSearchCV(pipe_ridge, param_grid_ridge, cv=5, scoring="neg_mean_squared_error")
grid_ridge.fit(X_train, y_train)
models["ridge"] = grid_ridge.best_estimator_

# ---- Lasso Regression (Grid Search) ----
param_grid_lasso = {"model__alpha": alpha}

pipe_lasso = Pipeline([
    ("scaler", StandardScaler()),
    ("model", Lasso(max_iter=5000, random_state=RANDOM_STATE))
])

grid_lasso = GridSearchCV(pipe_lasso, param_grid_lasso, cv=5, scoring="neg_mean_squared_error")
grid_lasso.fit(X_train, y_train)
models["lasso"] = grid_lasso.best_estimator_

# ---- ElasticNet (Grid Search) ----
param_grid_elastic = {
    "model__alpha": alpha,
    "model__l1_ratio": np.linspace(0.1, 0.9, 5)
}

pipe_elastic = Pipeline([
    ("scaler", StandardScaler()),
    ("model", ElasticNet(random_state=RANDOM_STATE))
])

grid_elastic = GridSearchCV(pipe_elastic, param_grid_elastic, cv=5, scoring="neg_mean_squared_error")
grid_elastic.fit(X_train, y_train)
models["elasticnet"] = grid_elastic.best_estimator_

# ================================
# 3. SAVE MODELS
# ================================
import os
os.makedirs("models", exist_ok=True)

for name, model in models.items():
    joblib.dump(model, f"models/{name}.pkl")
    print(f"Saved: models/{name}.pkl")

with open("models/feature_names.json", "w") as f:
    json.dump(feature_names, f)
print("Saved: models/feature_names.json")

print("\nAll 4 models successfully trained and saved!")